Terracotta-OSS/terracotta-utilities

tools/src/test/java/org/terracotta/utilities/io/FilesTestBase.java
Corrects a failure in `testCopyDirectoryRecursive` on a Mac when processing `missingLink`.
=> Correct testCopyDirectoryRecursive failure on macOS X

port-chooser/src/main/java/org/terracotta/utilities/test/net/PortManager.java, port-chooser/src/main/java/org/terracotta/utilities/test/net/SystemLevelLocker.java, test-tools/src/main/java/org/terracotta/utilities/test/Diagnostics.java, test-tools/src/test/java/org/terracotta/utilities/test/DiagnosticsTest.java, tools/src/main/java/org/terracotta/utilities/exec/Shell.java, tools/src/main/java/org/terracotta/utilities/io/Files.java, tools/src/main/java/org/terracotta/utilities/io/FilesSupport.java, tools/src/test/java/org/terracotta/utilities/io/FilesDeleteTest.java, tools/src/test/java/org/terracotta/utilities/io/FilesDeleteTreeTest.java, tools/src/test/java/org/terracotta/utilities/io/FilesEnvironmentTest.java, tools/src/test/java/org/terracotta/utilities/io/FilesRelocateDirectorySymlinkTest.java, tools/src/test/java/org/terracotta/utilities/io/FilesRelocateDirectoryTest.java, tools/src/test/java/org/terracotta/utilities/io/FilesRelocateFileSymlinkTest.java, tools/src/test/java/org/terracotta/utilities/io/FilesRelocateFileTest.java, tools/src/test/java/org/terracotta/utilities/io/FilesRelocateTest.java, tools/src/test/java/org/terracotta/utilities/io/FilesRelocateTestBase.java, tools/src/test/java/org/terracotta/utilities/io/FilesRenameTest.java, tools/src/test/java/org/terracotta/utilities/io/FilesTestBase.java
This commit stream corrects the following:
* Files.relocate relative target handling
* Files.relocate existing target w/o REPLACE_EXISTING
* Files.rename return with relative target
It also adds more testing for Files.relocate and Files.rename and makes a couple of other minor corrections.
Not that this commit stream does not alter the exceptions thrown in the event of an incompatible existing target -- normalization was considered but I thought a discussion should be had first.
=> Correct Files.relocate and Files.rename behavior

tools/src/main/java/org/terracotta/utilities/io/CapturedPrintStream.java, tools/src/main/java/org/terracotta/utilities/io/NullOutputStream.java, tools/src/main/java/org/terracotta/utilities/io/buffer/DumpUtility.java, tools/src/main/java/org/terracotta/utilities/logging/LoggerBridge.java, tools/src/main/java/org/terracotta/utilities/logging/LoggingOutputStream.java, tools/src/test/java/org/terracotta/utilities/io/CapturedPrintStreamTest.java, tools/src/test/java/org/terracotta/utilities/io/NullOutputStreamTest.java, tools/src/test/java/org/terracotta/utilities/logging/LoggerBridgeTest.java, tools/src/test/java/org/terracotta/utilities/logging/LoggingOutputStreamTest.java
This commit adds several classes to aid generation of diagnostic output:
* `LoggerBridge` and `LoggingOutputStream` to help with logging scenarios not easily addressed by SLF4J
* `CapturedPrintStream` and `NullOutputStream` to help in bridging stream output to the non-stream world
* `DumpUtility` to support "dumping" `Buffer` variants for visual examination
=> Add classes to help with logging and "live" diagnostic output.

test-tools/README.md, test-tools/src/main/java/org/terracotta/org/junit/rules/TemporaryFolder.java, test-tools/src/test/java/org/terracotta/org/junit/rules/TempFolderRuleTest.java
This commit picks up changes made to `TemporaryFolder` in JUnit 4.13.1 addressing CVE-2020-15250.
=> TemporaryFolder from JUnit 4.13.1

port-chooser/src/main/java/org/terracotta/utilities/test/net/PortManager.java, port-chooser/src/test/java/org/terracotta/utilities/test/net/PortManagerTest.java
This commit adds PortManager.getPortRef and PortManager.isReservablePort
methods that may be useful in certain usage scenarios.  It also adds an
PortRef.isClosed method.
=> Add PortManager methods

azure-pipelines.yml, port-chooser/src/main/java/org/terracotta/utilities/test/net/NetStat.java, port-chooser/src/main/java/org/terracotta/utilities/test/net/PortManager.java
This commit stream adds the `f` field designator (file descriptor) to the `lsof` `-F` option value to force the presence of the `f` (file descriptor) field in the `lsof` output used by `NetStat`.  (Newer versions include the field regardless of the presence of the `f` designator.)
This commit stream also attempts to disable the diagnostic port busy check (making use of `NetStat`) done by `PortManger` if `NetStat` fails.  (The typical usage model for `PortManager` results in multiple calls to `NetStat` and an environmental failure -- like an unexpected `lsof` output format -- can result in considerable noise.)
=> Correct `NetStat` processing for older versions of `lsof`

tools/src/main/java/org/terracotta/utilities/io/CapturedPrintStream.java, tools/src/test/java/org/terracotta/utilities/io/CapturedPrintStreamTest.java
This commit improves the utility of CapturedPrintStream for test development
by adding support for discarding the content (reset()) and obtaining the
encoded content (toByteArray()).
=> Add support for reset() and toByteArray() to CapturedPrintStream

test-tools/src/main/java/org/terracotta/utilities/test/Diagnostics.java
The documentation for `ThreadGroup.enumerate(Thread[], boolean)` says:
***If it is critical to obtain every active thread in this thread group, the
caller should verify that the returned int value is strictly less than the
length of list.***  This commit changed the behavior of `getAllThreads` to
conform to thad admonition.
=> Correct Diagnostics.getAllThreads behavior

tools/pom.xml, tools/src/main/java/org/terracotta/utilities/io/Files.java, tools/src/test/java/org/terracotta/utilities/io/FilesCopyTest.java, tools/src/test/java/org/terracotta/utilities/io/FilesStreamCopyTest.java, tools/src/test/resources/De_finibus_bonorum_et_malorum_Liber_Primus.txt
This commit adds support for a Files.copy(InputStream. Path, CopyOption...) method
mirroring the like named method in java.nio.file.Files.  The new implementation
handles "other process" interference when deleting the target (when REPLACE_EXISTING
is specified).
This commit stream resolves issue #10 .
=> Add support for Files.copy(InputStream, Path, CopyOption...)

test-tools/README.md, test-tools/src/test/java/org/terracotta/org/junit/rules/TemporaryFolderUsageTest.java
This commit changes test TemporaryFolderUsageTest.newFolderWithGivenFolderThrowsIOExceptionWhenFolderCannotBeCreated
to avoid failure when the newFolder operation actually succeeds. This
can happen when the user running the test has permissions allowing the write.
=> Avoid test failure when running CI as super-privileged user

test-tools/src/test/java/org/terracotta/utilities/test/DiagnosticsTest.java
This commit corrects for a race in the DiagnosticsTest.testDumpThreads test
where the assertion for a waiting thread is fails because the tested thread
has not yet reached the barrier.
=> Correct DiagnosticsTest.testDumpThreads failure

pom.xml, port-chooser/pom.xml, test-tools/pom.xml, tools/pom.xml
THis commit makes several dependency corrections:
* changes the scope of logback-classic from compile to test in the
terracotta-utilities-tools and terracotta-utilities-port-chooser modules
* Adjusted the Hamcrest vs JUnit dependencies
=> Correct dependency relationships

.github/workflows/ci.yaml, .github/workflows/publish-test-results.yaml
See for explanations: https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#support-fork-repositories-and-dependabot-branches
Fixes warning: *This action is running on a pull_request event for a fork repository. It cannot do anything useful like creating check runs or pull request comments. To run the action on fork repository pull requests, see https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#support-fork-repositories-and-dependabot-branches*
=> Allow test result publication for PR build

.github/workflows/ci.yaml, .github/workflows/publish-pr-test-results.yaml
See for explanations: https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#support-fork-repositories-and-dependabot-branches
Fixes warning: *This action is running on a pull_request event for a fork repository. It cannot do anything useful like creating check runs or pull request comments. To run the action on fork repository pull requests, see https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#support-fork-repositories-and-dependabot-branches*
=> Allow test result publication for PR build.

test-tools/src/main/java/org/terracotta/utilities/test/logging/ConsoleAppenderCapture.java, test-tools/src/test/java/org/terracotta/utilities/test/logging/ConsoleAppenderCaptureTest.java
This commit adds:
* support for identifying log capture threads in addition to the creating thread
* getting a list of the captured logging events
* clearing the captured log events
This update is added to enable use when the `ConsoleAppender` output to be captured is generated by a thread for which direct capture is not possible.  Since multiple threads are involved (at least the observer and the generator threads), synchronization is added for access to the captured output.  (`ListAppender` uses an unsynchronized `ArrayList`; however, `ListAppender` is based on `AppenderBase` which synchronizes on _itself_ when appending so access to the captured events is now synchronizing on the `ListAppender`.)
This is a _daggy_ commit stream.
=> Add support for supplemental threads to ConsoleAppenderCapture

test-tools/src/main/java/org/terracotta/utilities/test/matchers/ThrowsMatcher.java, test-tools/src/test/java/org/terracotta/utilities/test/matchers/ThrowsMatcherTest.java
This commit changes the behavior of ThrowsMatcher to retain the original
fault from the task being tested and use it in the fault description
instead of re-executing the task.  This avoids reporting issues with
non-idempotent tasks.
Fixes #51
=> Correct ThrowsMatcher fault description behavior

tools/src/main/java/org/terracotta/utilities/io/Files.java, tools/src/test/java/org/terracotta/utilities/concurrent/InterprocessCyclicBarrier.java, tools/src/test/java/org/terracotta/utilities/concurrent/InterprocessCyclicBarrierTest.java, tools/src/test/java/org/terracotta/utilities/io/FilesCreateTest.java, tools/src/test/resources/logback-test.xml
This commit adds a Files.createFile method that handles the
AccessDeniedException thrown from java.nio.file.Files.createFile
when the target file is just marked for deletion and not yet
deleted (Windows).
To support testing of this method, InterprocessCyclicBarrier is added
to permit test coordination among Java processes.
This commit resolves #50.
=> Add support for Files.createFile

pom.xml, port-chooser/pom.xml, port-chooser/src/main/java/org/terracotta/utilities/test/net/PortManager.java, port-chooser/src/main/java/org/terracotta/utilities/test/net/SystemLevelLocker.java, port-chooser/src/test/java/org/terracotta/utilities/test/net/PortManagerTest.java, test-tools/pom.xml, tools/pom.xml
This commit stream includes the following items:
* Correction to disabling the port release busy check -- corrects #54 
* Add options to PortRef.close to permit programmatically bypassing the port release busy check
* Changing the snapshot version from a 2-position (`0.0-SNAPSHOT`) to a 3-position (`0.0.13-SNAPSHOT`) value 
`PortRef.close(Set<CloseOption>)` is added to support cases where an unusual port allocation scheme is needed -- as is used in Galvan `org.terracotta.testing.master.AbstractHarnessEntry.chooseRandomPortRange` in which ports may be allocated but never used.
The snapshot version is changed to permit proper use of range-based versioning -- seems that both Maven and Gradle consider `0.0-SNAPSHOT` to be _less than_ `0.0.12`.
=> PortManager updates

pom.xml, test-tools/pom.xml, test-tools/src/test/java/org/terracotta/utilities/test/logging/ConsoleAppenderCaptureNoConsoleTest.java, test-tools/src/test/java/org/terracotta/utilities/test/logging/ConsoleAppenderCaptureTest.java
This commit shifts to the use of version ranges for SLF4J and logback.
SLF4J is capped at 1.7.9999 to avoid picking up 1.8.0-betaX releases
which will not work with released versions of Logback before 1.3.x.
The minimum versions of Logback is 1.2.11 which requires a minumum
version of SLF4J of 1.7.32.
While developing this update, it was observed that the SLF4J version
must "align" with the Logback version for Logback to be properly
initialized.  With this observation, tests for ConsoleAppenderCapture
are changed to terminate with a more informative assertion to avoid
an obscure test failure.
The configuration for the enforcer plugin is lifted out of an
execution configuration to permit its use as a top-level task.
=> Use version range for logging components

port-chooser/pom.xml, port-chooser/src/test/java/org/terracotta/utilities/test/net/PortManagerTest.java
This commit stream contains two items:
* Apply exclusion to correct dependency convergence failure
Module terracotta-utilities-port-chooser fails dependency convergence
verification because dependency convergence analysis fixes the version
of SLF4J used in terracotta-utilities-tools at the minimum version of
the range even though the dependency actually resolves the latest
available in the range.  The terracotta-utilities-port-chooser POM is
changed to exclude the SLF4J transitive dependency of
terracotta-utilities-tools in deference to the direct dependency.
* Avoid testExistingServerPort test timeout
PortManagerTest.testExistingServerPort times out when the test
environment has many open ports -- the PortRef release port busy
checking time is sensitive to the number of open ports.  Use …
=> Test & dependency (exclusion) update

.github/workflows/ci-javadoc.yaml, .github/workflows/ci.yaml, README.md, pom.xml, port-chooser/pom.xml, port-chooser/src/main/java/org/terracotta/utilities/test/net/EphemeralPorts.java, port-chooser/src/main/java/org/terracotta/utilities/test/net/NetStat.java, port-chooser/src/main/java/org/terracotta/utilities/test/net/PortManager.java, port-chooser/src/main/java/org/terracotta/utilities/test/net/ReservedPorts.java, port-chooser/src/test/java/org/terracotta/utilities/test/net/NetStatTest.java, port-chooser/src/test/java/org/terracotta/utilities/test/net/PortManagerTest.java, port-chooser/src/test/java/org/terracotta/utilities/test/net/TestSupport.java, tools/src/main/java/org/terracotta/utilities/io/Files.java, tools/src/test/java/org/terracotta/utilities/io/FilesRelocateTest.java, tools/src/test/java/org/terracotta/utilities/io/FilesTestBase.java
This commit stream includes the commits from PR #60 and PR #61 and closes issue #59.
This commit stream includes the following, mostly related to PortManager and NetStat:
* Add DISABLE_PORT_RELEASE_CHECK environment variable
This commit enables the use of the 'DISABLE_PORT_RELEASE_CHECK' environment variable to, when set to 'true', disable the port release check performed by PortManager.
* Treat TIME_WAIT as normal TCP connection status
This commit removes TCP connections in a TIME_WAIT status from the results displayed by the port release check performed by PortManager.
This commit also adds Javadoc for NetStat.BusyPort.TcpState describing the possible TCP connection state transitions. The diagrams in the documentation require Java 11+ to generate and, for a _complete_ build, now …
=> PortManager and NetStat updates

pom.xml
This commit updates the Spotbugs dependency to permit building under a Java 17 JDK.
=> Update Spotbugs to permit build under Java 17

port-chooser/src/main/java/org/terracotta/utilities/test/net/PortManager.java
This commit removes the import for AccessController and fully-qualifies the reference to enable proper warning suppression in Java 17+
This is a daggy fix.
(I ran into this when compiling under Java 17 using Gradle.  For some reason, the same failure doesn't occur under Maven.  There are some option differences between the two but I didn't bother to work out the trigger.)
=> Isolate reference to java.security.AccessController for Java 17+

buildSrc/src/main/kotlin/org.terracotta.java-conventions.gradle.kts, port-chooser/build.gradle.kts, test-tools/build.gradle.kts, tools/build.gradle.kts
This commit sets the POM name and URL that were missing from the generated POM of each project and flagged during Sonatype repository verification.
=> Correct Sonatype verification issues with generated POMs

buildSrc/src/main/kotlin/org.terracotta.java-conventions.gradle.kts, test-tools/build.gradle.kts
This commit corrects the Specification-Title in MANIFEST.MF and adds the
JUnit license files to the terracotta-utilities-test-tools executable
jar (as well as the sources jar).
=> MANIFEST.MF and LICENSE corrections

build.gradle.kts
The goal is to have the following do most of the work:
```bash 
./gradlew release -Prelease.useAutomaticVersion=true -PpostReleaseBuildTasks="closeSonatypeStagingRepository"
```
1. tag (remove -SNAPSHOT)
2. build/test
3. publish tag to sonatype
4. close sonatype repo
5. move to next snapshot / commit
This **does not push tag or snapshot increment commit**.    I expect to make that a step in the job unless someone has a different opinion.
=> gradle: releaser - publish relationship

.github/workflows/ci.yaml, buildSrc/src/main/kotlin/org.terracotta.java-conventions.gradle.kts, gradle.properties, gradle/wrapper/gradle-wrapper.properties, gradlew, port-chooser/src/main/java/org/terracotta/utilities/test/net/NetStat.java, test-tools/src/main/java/org/terracotta/utilities/test/Diagnostics.java, test-tools/src/test/java/org/terracotta/utilities/test/DiagnosticsTest.java, tools/src/main/java/org/terracotta/utilities/exec/Shell.java
This commit introduces Java 21 into the build/test matrix and  changes code to avoid compilation faults arising from Java 17+ changes.
=> Enable building & testing with Java 21
